server:
  port: 8181
error:
  include-message: always

info:
  app:
    description: sample application
    name: MyCarMarket
    version: 1.0.0
logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, metrics, threaddump, heapdump, shutdown,
          beans
  trace:
    http:
      enabled: true
      
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${JDBC_DATABASE_URL:localhost}:5432/car_market?createDatabaseIfNotExist=true&amp"
    username: "${JDBC_DATABASE_USERNAME:postgres}"
    password: "${JDBC_DATABASE_PASSWORD:****}"
  thymeleaf:
    mode: HTML

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      show_sql: true
      use_sql_comments: true
#  main:
#    allow-circular-reference: true
#    allow-bean-definition-overriding: true

#Facebook login config
  security:
    oauth2:
      client:
         registration:
           facebook:
               client-id: 452187580203704
               client-password: 4629b0cfc49f04da5208997d2d587103

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#password
app:
  default:
    admin:
      password: 1234

#Cloudinary Properties
cloudinary:
  cloud-name: djklypnmm
  api-key: 168879155711435
  api-secret: avHbGBij5NgNmX46QLK6VYu3UIE
#Multipart config
# multipart
  multipart.enabled: true
  spring.http.multipart.max-file-size: 500000KB
  spring.http.multipart.max-request-size: 500000KB