server:
  port: 8181
error:
  include-message: always

info:
  app:
    description: sample application
    name: MyCarMarket
    version: 1.0.0
logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, httptrace, metrics, threaddump, heapdump, shutdown,
          beans
  trace:
    http:
      enabled: true
      
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_market?createDatabaseIfNotExist=true&amp
    username: root
    password: A4620692!
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      show_sql: true
      use_sql_comments: true
#  main:
#    allow-circular-reference: true
#    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
         registration:
           facebook:
               client-id: 452187580203704
               client-password: 4629b0cfc49f04da5208997d2d587103

  mvc:
    hiddenmethod:
      filter:
        enabled: true

app:
  default:
    admin:
      password: topsecret
